CREATE TABLE CRI_CRIATURA(
  CRI_NOME VARCHAR2(30),
  CONSTRAINT CRI_PK PRIMARY KEY (CRI_NOME),
  CRI_ATAQUE NUMBER(5),
  CRI_ESTAMINA NUMBER(5),
  CRI_DEFESA NUMBER(5),
  CRI_ALTURA NUMBER(5),
  CRI_PESO NUMBER(5),
  CRI_CHANCE_CAPTURA NUMBER(5)
);

CREATE TABLE TIP_TIPO (
  TIP_NOME VARCHAR2(10),
  CONSTRAINT TIP_PK PRIMARY KEY (TIP_NOME)
);

CREATE TABLE CRT_CRIATURA_TIPO (
  CRI_NOME VARCHAR2(30),
  CONSTRAINT CRT_CRI_FK FOREIGN KEY (CRI_NOME) REFERENCES CRI_CRIATURA (CRI_NOME),
  TIP_NOME VARCHAR2(10),
  CONSTRAINT CRT_TIP_FK FOREIGN KEY (TIP_NOME) REFERENCES TIP_TIPO (TIP_NOME)
);

CREATE TABLE HAB_HABILIDADE (
  HAB_NOME VARCHAR2(20),
  CONSTRAINT HAB_PK PRIMARY KEY (HAB_NOME),
  HAB_PODER_ATAQUE NUMBER(5),
  TIP_NOME VARCHAR2(10),
  CONSTRAINT HAB_FK FOREIGN KEY (TIP_NOME) REFERENCES TIP_TIPO (TIP_NOME)
);

CREATE TABLE CRH_CRIATURA_HABILIDADE (
  CRI_NOME VARCHAR2(30),
  CONSTRAINT CRH_CRI_FK FOREIGN KEY (CRI_NOME) REFERENCES CRI_CRIATURA (CRI_NOME),
  HAB_NOME VARCHAR2(20),
  CONSTRAINT CRH_HAB_FK FOREIGN KEY (HAB_NOME) REFERENCES HAB_HABILIDADE (HAB_NOME)
);

CREATE TABLE LOC_LOCAL (
  LOC_LATITUDE NUMBER(10,5),
  LOC_LONGITUDE NUMBER(10,5),
  CONSTRAINT LOC_PK PRIMARY KEY (LOC_LATITUDE, LOC_LONGITUDE),
  LOC_NOME VARCHAR2(20),
  LOC_SEGURO VARCHAR2(1)
);

CREATE TABLE CRL_CRIATURA_LOCAL (
  CRI_NOME VARCHAR2(30),
  CONSTRAINT CRL_CRI_FK FOREIGN KEY (CRI_NOME) REFERENCES CRI_CRIATURA (CRI_NOME),
  LOC_LATITUDE NUMBER(10,5),
  LOC_LONGITUDE NUMBER(10,5),
  CONSTRAINT CRL_LOC_FK FOREIGN KEY (LOC_LATITUDE, LOC_LONGITUDE) REFERENCES LOC_LOCAL (LOC_LATITUDE, LOC_LONGITUDE),
  CONSTRAINT CRL_PK PRIMARY KEY (CRI_NOME, LOC_LATITUDE, LOC_LONGITUDE),
  CRL_CHANCE NUMBER(5)
);

CREATE TABLE PUB_PUBLICO (
  LOC_LATITUDE NUMBER(10,5),
  LOC_LONGITUDE NUMBER(10,5),
  CONSTRAINT PUB_LOC_FK FOREIGN KEY (LOC_LATITUDE, LOC_LONGITUDE) REFERENCES LOC_LOCAL (LOC_LATITUDE, LOC_LONGITUDE),
  CONSTRAINT PUB_PK PRIMARY KEY (LOC_LATITUDE, LOC_LONGITUDE)
);

CREATE TABLE PRI_PRIVADO (
  LOC_LATITUDE NUMBER(10,5),
  LOC_LONGITUDE NUMBER(10,5),
  CONSTRAINT PRI_PK PRIMARY KEY (LOC_LATITUDE, LOC_LONGITUDE),
  PRI_TAXA_ACESSO NUMBER(5,2),
  PRI_HORARIO_FUNCIONAMENTO VARCHAR2(10)
);

ALTER TABLE PRI_PRIVADO ADD CONSTRAINT PRI_FK FOREIGN KEY (LOC_LATITUDE, LOC_LONGITUDE) REFERENCES LOC_LOCAL (LOC_LATITUDE, LOC_LONGITUDE);
