-- QUESTAO 01
  --A)
CREATE TABLE VIS_VISITA(
  IMO_CEP NUMBER(8),
  IMO_NUMERO NUMBER(5),
  VIS_DATA_VISITA DATE,
  VIS_OBSERVACAO VARCHAR2(255),
  CONSTRAINT VIS_PK PRIMARY KEY (IMO_CEP, IMO_NUMERO, VIS_DATA_VISITA)
);
  --B)
ALTER TABLE VIS_VISITA ADD CONSTRAINT VIS_IMO_FK FOREIGN KEY (IMO_CEP, IMO_NUMERO) 
  REFERENCES IMO_IMOVEL (IMO_CEP, IMO_NUMERO);

  --C) TO_DATE('2016-10-02 12:45:15', 'YYYY-MM-DD HH24:MI:SS')
INSERT INTO VIS_VISITA (IMO_CEP, IMO_NUMERO, VIS_DATA_VISITA) VALUES
  (12372190, 25, TO_DATE('10/01/2016' ,'DD-MM-YYYY'));
INSERT INTO VIS_VISITA (IMO_CEP, IMO_NUMERO, VIS_DATA_VISITA, VIS_OBSERVACAO) VALUES
  (12372190, 7, TO_DATE('10/01/2016' ,'DD-MM-YYYY'), 'Morador não encontrado');
INSERT INTO SEN_SENSOR (SEN_ID, IMO_CEP, IMO_NUMERO, SEN_TIPO) VALUES
  (SEN_SEQ.NEXTVAL, 12372190, 25, 'GAS');
  
  --D)
SELECT SEN_SEQ.CURRVAL FROM DUAL;
UPDATE SEN_SENSOR SET SEN_TIPO = 'PRESENCA' WHERE SEN_ID = 5;

  --E)
DELETE FROM SEN_SENSOR WHERE SEN_ID = 5;

  --F)
SELECT DISTINCT IMO_IMOVEL.IMO_CEP, IMO_IMOVEL.IMO_NUMERO, IMO_IMOVEL.IMO_CONTATO 
  FROM IMO_IMOVEL JOIN SEN_SENSOR ON 
  SEN_SENSOR.IMO_CEP = IMO_IMOVEL.IMO_CEP AND 
  SEN_SENSOR.IMO_NUMERO = IMO_IMOVEL.IMO_NUMERO 
  WHERE SEN_SENSOR.SEN_TIPO = 'Gás';

  --G)
SELECT IMO_IMOVEL.IMO_CEP, IMO_IMOVEL.IMO_NUMERO, IMO_IMOVEL.IMO_CONTATO 
  FROM IMO_IMOVEL JOIN SEN_SENSOR ON 
  IMO_IMOVEL.IMO_CEP = SEN_SENSOR.IMO_CEP AND
  IMO_IMOVEL.IMO_NUMERO = SEN_SENSOR.IMO_NUMERO 
  WHERE SEN_SENSOR.SEN_ID NOT IN (SELECT SEN_ID FROM MED_MEDICAO);

  --H) SENSOR 3 TEM QUE APARECER
SELECT IMO_IMOVEL.IMO_CEP, IMO_IMOVEL.IMO_NUMERO FROM IMO_IMOVEL JOIN SEN_SENSOR ON 
  SEN_SENSOR.IMO_CEP = IMO_IMOVEL.IMO_CEP AND 
  SEN_SENSOR.IMO_NUMERO = IMO_IMOVEL.IMO_NUMERO JOIN 
    (SELECT T1.SEN_ID AS MED_SEN_ID FROM MED_MEDICAO T1 JOIN 
    MED_MEDICAO T2 ON T1.SEN_ID = T2.SEN_ID AND 
    T1.MED_LEITURA * 1.2 > T2.MED_LEITURA AND 
    T1.MED_DT_HR > T2.MED_DT_HR) ON SEN_SENSOR.SEN_ID = MED_SEN_ID;

  --I)
CREATE USER SENSOR IDENTIFIED BY 123;
GRANT CREATE SESSION TO SENSOR;
GRANT INSERT, UPDATE ON imb003.MED_MEDICAO TO SENSOR;

  --J)
CREATE OR REPLACE VIEW SENSOR_IMOVEL AS
  SELECT DISTINCT IMO_CEP, IMO_NUMERO, SEN_TIPO FROM SEN_SENSOR;