CREATE TABLESPACE  TS_BDP1_2016
DATAFILE  '/mnt/Data/Google-Drive-bustamantecamilo23/FATEC/3_SEM/Programacao_BD/BDs/TS_BDP1_2016.dbf' SIZE 1M 
AUTOEXTEND ON;

CREATE USER USER_PRATICA05
IDENTIFIED BY aluno
DEFAULT TABLESPACE TS_BDP1_2016
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON TS_BDP1_2016;

GRANT DBA TO USER_PRATICA05 WITH ADMIN OPTION;